language: java
node_js:
  - "0.10"

before_install: npm install -g grunt-cli
install: npm install

before_install: npm install -g bower
install: bower install

script: gradle build

notifications:
  email:
    recipients:
      - os-v20-devs@krishagni.com
    on_success: always
    on_failure: always

branches:
  only:
    - OS_v20
